name: Working Dirs and Shells

on: [push]

jobs:
    display-wd-info-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Display Working Directory & List Files
              run: |
                echo "Working Directory"
                pwd
                echo "List all files / folders"
                ls -a
                echo "Github Built-in Variables"
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
    display-wd-info-windows:
        runs-on: windows-latest
        steps:
            - name: Display Working Directory & List Files
              run: |
                echo "Working Directory"
                pwd
                echo "List all files / folders"
                ls -a
                echo "Github Built-in Variables"
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
