name: Working Dirs and Shells

on: [push]

defaults: 
    run:
        shell: bash
        # working-directory: /de/ed
jobs:
    display-wd-info-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Display Working Directory & List Files
              run: |
                echo "Working Directory"
                pwd
                echo "List all files / folders"
                ls -a
                echo "Github Built-in Variables"
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
            - name: Change working directory
              working-directory: /home/runner
              run: pwd
    display-wd-info-windows:
        runs-on: windows-latest
        defaults:
            run:
                shell: pwsh
        steps:
            - name: Display Working Directory & List Files
              run: |

                echo "Working Directory"
                Get Location
                echo "List all files / folders"
                dir
                echo "Github Built-in Variables"
                echo $env:GITHUB_SHA
                echo $env:GITHUB_REPOSITORY
                echo $env:GITHUB_WORKSPACE
            - name: Python Shell
              shell: python
              run: |
                import platform
                print(platform:processor())
